// Importing JSON data for various categories (personal, talks, publications, etc.)
import personalData from '../../static/author_data/personal_data.json' with { type: "json" };
import talksData from '../../static/autogenerated_files/json_files/talks.json' with { type: "json" };
import publicationsData from '../../static/autogenerated_files/json_files/publications.json' with { type: "json" };
import preprintsData from '../../static/autogenerated_files/json_files/preprints.json' with { type: "json" }; 

import { populateTable, populateEducation, populateExperience, renderCsv, displayArticles } from './utils.js';

/**
 * Populates the personal data section in the HTML with the data from the JSON.
 * @param {Object} personalData - The object containing personal data of the author.
 */
function populatePersonalInformation(personalData) {
    console.log(personalData);

    // Populate the name, title, and biography sections
    document.getElementById('name').innerHTML = personalData.name;
    document.getElementById('title').innerHTML = personalData.title;
    document.getElementById('biography-text').innerHTML = personalData.biography;

    // Populate the list of interests
    const interestsListElement = document.getElementById('interests-list');
    personalData.interests.forEach(interest => {
        const interestListItem = document.createElement('li');
        interestListItem.innerHTML = interest;
        interestsListElement.appendChild(interestListItem);
    });
}

/**
 * Initialize the page content by populating personal data and rendering CSV tables and articles.
 */
function initializePageContent() {
    // Populate personal information from JSON data
    populatePersonalInformation(personalData);

    // Render the CSV data as HTML tables
    renderCsv("../static/author_data/education.csv", 'education-list', populateEducation);
    renderCsv("../static/author_data/professional_experience.csv", 'professional-experience-list', populateExperience);
    renderCsv("../static/author_data/students.csv", 'students-table', populateTable);

    // Display articles (talks, publications, preprints) in the respective sections
    displayArticles(talksData, 'talks-list', 'talks', 3);
    displayArticles(publicationsData, 'publications-list', 'publications', 3);
    displayArticles(preprintsData, 'preprints-list', 'preprints', 3);
}

// Wait for the document to fully load before executing the initialization
document.addEventListener('DOMContentLoaded', initializePageContent);




